### PR TITLE
Require matplotlib v3.5+.

### PR DESCRIPTION
**Pull request by thetorpedodog**
scanpy requires `matplotlib.colormaps`, which is not in 3.4.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Attempt number two, this time from a personal repo. (Previously, #11.)

### CODE REVIEW

**Comment by thetorpedodog** [comment]
@conda-forge-admin, please rerender

**Comment by thetorpedodog** [comment]
@conda-forge-admin, please rerender

(asking again because apparently it is very picky about repo names)

**Comment by flying-sheep** [comment]
Since @ivirshup is working on minimum deps, he should be the one of the two of us to check this out!

**Comment by ivirshup** [comment]
I can confirm that scanpy is more broken with matplotlib 3.4 than 3.5. But I also get an error on 3.5

```
FAILED scanpy/tests/test_embedding_plots.py::test_missing_values_continuous[pca-na_color.black_tup-legend.off-vbounds.percentile] - AttributeError: 'ColormapRegistry' object has no attribute 'get_cmap'
```

I think this was actually due to a recent change. This only works in 3.6+

Buuuut, Q4 2023 (e.g. now) is the [recommended time to drop support for matplotlib 3.5](https://scientific-python.org/specs/spec-0000/#2023---quarter-4), so it may be reasonable to just bump this to 3.6.

**Comment by ivirshup** [comment]
WDYT?

**Comment by thetorpedodog** [comment]
> I can confirm that scanpy is more broken with matplotlib 3.4 than 3.5. But I also get an error on 3.5
> 
> ```
> FAILED scanpy/tests/test_embedding_plots.py::test_missing_values_continuous[pca-na_color.black_tup-legend.off-vbounds.percentile] - AttributeError: 'ColormapRegistry' object has no attribute 'get_cmap'
> ```
> 
> I think this was actually due to a recent change. This only works in 3.6+
> 
> Buuuut, Q4 2023 (e.g. now) is the [recommended time to drop support for matplotlib 3.5](https://scientific-python.org/specs/spec-0000/#2023---quarter-4), so it may be reasonable to just bump this to 3.6.

Sounds good to me. I was going based on a report that a fresh installation failed immediately on `import scanpy` with matplotlib v3.4 installed and tested specifically that far and not gone into detail.

**Review by ivirshup — APPROVED** [review]
Great. Thanks for this and the PR to scanpy!
